### ISSUE TITLE
Using Wiring with Visual Basic (e.g. with Excel)

### ISSUE THREAD

**Issue by chatelao** [ms-iot/remote-wiring-experience#10]
Hi,

Is there somewhere an example using Firmata with Visual Basic, maybe with a small wrapper DLL or similar?

**Comment by zfields** [comment]
To answer your question, Yes, you can use Visual Basic.

I know it can be confusing, but this repository is for the Universal Windows Aapplication named `remote-wiring-experience`. Sorry for the delayed response, but we normally see questions like these on the repository of the underlying technology, known as `remote-wiring` (https://github.com/ms-iot/remote-wiring).

`remote-wiring` is available in NuGet form and can be added to your Visual Basic project through the NuGet package manager.
